site_name: Receita Federal

repo_name: "2025.1-ReceitaFederal"
repo_url: "https://github.com/Requisitos-de-Software/2025.1-ReceitaFederal.git"
site_url: "https://requisitos-de-software.github.io/2025.1-ReceitaFederal/"

extra_css:
  - stylesheets/extra.css


theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark-blue  
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dark-blue   
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: assets/receita-federal.png 
  favicon: assets/receita-federal.ico
    

nav:
  - Início: index.md
  - Guias: 
      - Tutorial mkdocs: guias/tutorial-mkdocs.md
  - Apresentações: 
      - Apresentação 1 (Etapa 01): apresentacoes/apresentacao1.md
      - Apresentação 2 (Etapa 02): apresentacoes/apresentacao2.md
      - Apresentação 3 (Etapa 03): apresentacoes/apresentacao3.md
      - Apresentação 4 (Etapa 04): apresentacoes/apresentacao4.md
      - Apresentação 5 (Etapa 06): apresentacoes/apresentacao5.md
      - Apresentação 6 (Etapa 05): apresentacoes/apresentacao6.md
  - Inspeção: 
      - Entrega 01 (Etapa 01):
          - Grupo 6: inspecao/entrega01/inspecao-grupo6.md
          - Grupo +1: inspecao/entrega01/inspecao-grupo7.md
      - Entrega 02 (Etapa 02):
          - Grupo 6: inspecao/entrega02/inspecao-grupo6.md
          - Grupo +1: inspecao/entrega02/inspecao-grupo7-2.md
      - Entrega 03 (Etapa 03):
          - Grupo 6: inspecao/entrega03/inspecao-grupo6-3.md
          - Grupo +1: inspecao/entrega03/inspecao-grupo7-3.md
      - Entrega 04 (Etapa 04)::
          - Grupo 6: inspecao/entrega04/inspecao-grupo6-4.md
          - Grupo +1: inspecao/entrega04/inspecao-grupo7-4.md
      - Entrega 05 (Etapa 06):
          - Grupo 6: inspecao/entrega05/inspecao-grupo6-5.md
          - Grupo +1: inspecao/entrega05/inspecao-grupo7-5.md
      - Entrega 06 (Etapa 05):
          - Grupo +1: inspecao/entrega06/inspecao-grupo7-6.md
  - Atas: 
      - Ata 01 (11/04/2025): atas/ata1.md
      - Ata 02 (19/04/2025): atas/ata2.md
      - Ata 03 (21/04/2025): atas/ata3.md
      - Ata 04 (09/05/2025): atas/ata4.md
      - Ata 05 (25/05/2025): atas/ata5.md
      - Ata 06 (13/06/2025): atas/ata6.md
  - Pré-Rastreabilidade: 
      - RichPicture: pre-rastreabilidade/richpicture.md
  - Planejamento: 
      - App selecionado: planejamento/selecao-app.md
      - Ferramentas: planejamento/ferramentas.md
      - Heatmap: planejamento/heatmap.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma Executado: planejamento/cronograma-executado.md
  - Elicitação: 
      - Personas: elicitacao/personas.md
      - Storytelling: elicitacao/storytelling.md
      - Análise de documentos: elicitacao/analisededocumentos.md
      - Introspecção: elicitacao/introspeccao.md
      - Entrevista: elicitacao/entrevista.md
      - Priorização:
          - First Things First: elicitacao/priorizacao/ftf.md
          - MoSCoW: elicitacao/priorizacao/MoSCoW.md
          - 100$: elicitacao/priorizacao/100$.md
          - QFD: elicitacao/priorizacao/QFD.md
      - Requisitos Elicitados: elicitacao/requisitos-elicitados.md
  - Modelagem: 
      - Cenários: modelagem/cenarios.md
      - Casos de uso: modelagem/casosdeuso.md
      - Léxicos: modelagem/lexicos.md
      - Especificação Suplementar: modelagem/especificacao-suplementar.md
  - Modelagem ágil: 
      - NFR Framework: modelagem-agil/nfr-framework.md
      - Histórias de usuário: modelagem-agil/historias-usuario.md
      - Backlog: modelagem-agil/backlog.md
  - Rastreabilidade: 
      - Matriz Geral: rastreabilidade/matriz-geral.md  
      - Pós-Rastreabilidade: rastreabilidade/pos-rastreabilidade.md
  - Verificação: 
      - Planejamento geral: verificacao/planejamento-geral.md
      - Entrega 01:
          - Planejamento de verificação - Entrega 01: verificacao/entrega1/planejamento1.md
          - Rich Picture: verificacao/entrega1/richpicture-ver.md
      - CONTINUA AQUI: mudarisso/mudar.md

      - Entrega 03:
          - Planejamento de verificação - Entrega 03: verificacao/entrega3/planejamento3.md
          - Cenários: verificacao/entrega3/lista-cenarios.md
          - Léxicos: verificacao/entrega3/lista-lexicos.md
          - Casos de uso: verificacao/entrega3/lista-casosdeuso.md
          - Especificação Suplementar: verificacao/entrega3/lista-espsup.md    
      - Entrega 04:
          - Planejamento de verificação - Entrega 04: verificacao/entrega4/planejamento4.md
          - NFR Framework: verificacao/entrega4/lista-nfrframework.md
          - Histórias de usuário: verificacao/entrega4/lista-us.md
          - Backlog: verificacao/entrega4/lista-backlog.md
  - Validação: 
      - Prototipação: validacao/prototipacao.md
      - Comprovação Informal: validacao/comprovante-informal.md 

